name: deploy-docs

on:
  push:
    branches:
      - main

jobs:
  Job:
    runs-on: ubuntu-latest
    steps:
      - name: Convert Markdown to HTML
        uses: natescherer/markdown-to-html-with-github-style-action@v1
        with:
          path: README.md,CHANGELOG.md
          outputpath: docs
          matchpathstructure: true

      - name: Deploy to GitHub Pages (docs branch) 🚀
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.ACCESS_TOKEN }}
          publish_branch: docs
          publish_dir: ./docs
          force_orphan: true